### ISSUE TITLE
misleading Encryption Key value

### ISSUE THREAD

**Issue by finoradin** [MediaArea/MediaTrace#9]
When testing the [sample DPX file](https://github.com/MediaArea/MediaTrace/blob/master/TraceSamples/000001.dpx), I see that the value for `<data offset="660" name="Encryption key">` is `4294967295`

Yet when I look at the file at offset 660 I see the standard `FFFFFFFF` which indicates that the image data is not encrypted. What is `4294967295`?

**Comment by dericed** [comment]
The value is presented as a decimal rather than hexadecimal.

**Comment by finoradin** [comment]
oh well that explains it – what is the intent in using decimal? Are there any other values that are represented in decimal?

**Comment by dericed** [comment]
We've been considering adding an attribute later to state the expression type (hex, dec, string) later, but currently decimal is the default in cases like this. For mediatrace it isn't really suppose to provide the format context that would inform whether a value would prefer a decimal or hexadecimal traditional presentation but be a very generic documentation structure of a file format. Because of the decimal preference in  cases like frame height we'll say 480 instead of 1E0 and 4294967295 instead of FFFFFFFF. To know if hexadecimal is a more apt expression is a bit of a matter of tradition, usually the computer reads this info rather than a human.

**Comment by finoradin** [comment]
Understood

**Comment by dericed** [comment]
B)
